name: CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Especifica la versión de Node.js que necesitas

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production     

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Push Docker image
      with:
        image: sergio0017/api-bff-nestjs
        tags: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: sergio0017
        password: Sergio#17
    - name: Clone deplyment repository
      env:
        EXTERNAL_REPO: 'https://github.com/checho0017/Charts.git'
        BRANCH: 'main'
      run: |
        cd ..
        git clone --single-branch --branch ${{ env.BRANCH }} ${{ env.EXTERNAL_REPO }} Charts
        cd Charts
        ls
    - name: yq - portable yaml processor
      uses: mikefarah/yq@v4.44.3
    - name: Set new image tag
      env: 
        IMAGE_NAME: sergio0017/api-bff-nestjs
      run: |
        cd ..
        ls
        cd Charts/apichart
        ls
        yq eval ".versionImage = \"${{ env.IMAGE_NAME }}:${{ github.sha }}\"" -i values.yaml
    - name: Commit changes in external repo
      env:
        GITHUB_TOKEN: ${{ secrets.CLALVEACCESO }}
      run: |
        cd ..
        cd Charts
        ls
        git config  user.email "action@github.com"
        git config  user.name "GitHub Action"
        git add .
        git commit -m "Actualiza el nombre de la imagen a ${{ env.IMAGE_NAME }}:${{ github.sha }}"
        echo "Usando la clave API: ${{ env.GITHUB_TOKEN }}"
        git remote set-url origin https://checho0017:${{ env.GITHUB_TOKEN }}@github.com/checho0017/Charts.git 
        echo git remote -v
        git push origin main

        